# Generated by Django 4.2.3 on 2023-08-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Опубликовано'),
        ),
    ]
